Update ftgl discovery and usage
Search for <FTGL/ftgl.h> instead of <FTGL/FTGL.h>

/usr/include/FTGL/FTGLBitmapFont.h:29:5: error: #warning This header is deprecated. Please use <FTGL/ftgl.h> from now. [-Werror=cpp]
   29 | #   warning This header is deprecated. Please use <FTGL/ftgl.h> from now.
      |     ^~~~~~~