Add missing braces
src/libgluonbase/screen.cc:74:25: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
   74 |                         if (_sdl_surface)
      |                         ^~
src/libgluonbase/screen.cc:77:33: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
   77 |                                 break;
      |                                 ^~~~~